### ISSUE TITLE
FEATURE REQUEST Bot Join channel and spectate. no capture program.

### ISSUE THREAD

**Issue by napster85** [tanndev/silence-among-us#50]
I good feature would be for the bot to spectate a live stream of someone in the channel in order to check for the "Shhhh" and "discussion"  screens. (maybe dead bodies too?) 
so it removes the need for one of the players to use the capture program.

**Comment by jftanner** [comment]
That's an extremely complicated feature to implement, since it requires several components:
- Dynamically process a video stream through discord
- Scan that stream via OCR (or similar) to identify game events
- Reliably identify, from screen events, which players are alive and dead.

Beyond the complexity, there's also some technical hurdles. The biggest of which is processing power and bandwidth. Receiving and processing the video stream would be an extremely resource intensive operation. The cost to maintain the (free) bot would rapidly become unsustainable.

So, while I appreciate the creative problem solving, I'm afraid there's no way I can reasonably consider this implementation.

**Comment by jftanner** [comment]
In the name of thoroughness, I went and checked the APIs to see if this was even theoretically possible (for, say, a premium feature.) Turns out, there's no API for bots to even _watch_ streams. So I don't think this is possible with the Discord API.
