### ISSUE TITLE
unable to delete messages which contain commands for the bot

### ISSUE THREAD

**Issue by Giganox** [tanndev/silence-among-us#57]
## Bug Report
Commands like "!sau start", "!sau config set speech off" or "!sau config get prefix" can not be deleted out of Discord channels by users/moderators/admins.
I assume that's due to the bot still accessing those messages (?)

### Steps to Reproduce
- type "!sau help" in a channel the bot has Access to.
(the bot will provide the help page)
- try to delete your own message "!sau help".
(you should notice that the message does not get deleted)

### Expected behavior
I would expect the bot delete the command messages automatically or at least not prevent users from deleting them.

**Comment by jftanner** [comment]
I can guarantee that the bot isn't preventing you from deleting messages. (Because that's actually impossible in the API. I couldn't do that if I wanted to.)

In fact, the bot deletes commands on its own as well. (Assuming it has permissions to do so.)

One thing I _have_ seen in local testing is a kind of "ghost message" getting left behind, but _only_ for the person who posted it. The message isn't actually on the server anymore, but the sending client has a copy of it locally. I think it's essentially a race condition inside the Discord client. Unfortunately, the user can't delete it because it doesn't exist.

Could that be what you're seeing?

**Comment by Giganox** [comment]
Seems like you are right. Sorry for bothering you.
Thank you for your efforts and please keep up the good work!

**Comment by jftanner** [comment]
No worries!

I hit my head against that particular bug for quite a while before I finally figured it out. Hopefully they fix it.
